### ISSUE TITLE
Permission denied on PBS server

### ISSUE THREAD

**Issue by arahuja** [hammerlab/stratotemplate#14]
Used this to re-create a new cluster from scratch.  Cluster up seems successful but on submitting a workflow I see:

```
SSH failed:Warning: Permanently added 'arahuja-strat-pbs-server,10.142.15.192' (ECDSA) to the list of known hosts.
 Permission denied (publickey)
```

**Comment by smondet** [comment]
Did you refollow the whole process or are you reusing the Ketrew server?

If reusing: 
a fresh version of `gcpketrew.sh` has the sub-command `pubkey`, you can copy-paste that into the `$HOME/.ssh/authorized_keys` of the `$PREFIX-user` user on `$PREFIX-pbs-server`.

**Comment by arahuja** [comment]
Whole process from 'Get a Ketrew server'

**Comment by smondet** [comment]
AFAIK this was fixed by https://github.com/hammerlab/stratocumulus/pull/49
