### ISSUE TITLE
Have to sudo in order to run sh gcpketrew.up

### ISSUE THREAD

**Issue by ihodes** [hammerlab/stratotemplate#2]
Otherwise I get 

```
ERROR: (gcloud.components.install) You cannot perform this action because you do not have permission to modify the Google Cloud SDK installation directory [/usr/lib/google-cloud-sdk].
```

**Comment by smondet** [comment]
Did you install the extra gcloud as a user or root?

![](https://www.dropbox.com/s/bkllcji1lat13bl/Screenshot%202016-07-15%2016.14.44.png?raw=1)

**Comment by ihodes** [comment]
Don't recall; had it previous install, so probably so? Fine to close this out, didn't break anything and it's probably my previous install that was the issue.

**Comment by smondet** [comment]
The instructions ask you to install a fresh `gcloud` because the one on the `compute-rw` nodes is not fully capable.
